/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProductComponent: typeof import('./src/components/AddProductComponent.vue')['default']
    AddPromtoionButtonComponent: typeof import('./src/components/AddPromtoionButtonComponent.vue')['default']
    AdminHeader: typeof import('./src/components/AdminHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    CartPage: typeof import('./src/components/CartPage.vue')['default']
    CheckoutPage: typeof import('./src/components/CheckoutPage.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FooterPage: typeof import('./src/components/FooterPage.vue')['default']
    InventoryTab: typeof import('./src/components/InventoryTab.vue')['default']
    JewelleryProductLayout: typeof import('./src/components/JewelleryProductLayout.vue')['default']
    LayoutPage: typeof import('./src/components/LayoutPage.vue')['default']
    MenHeader: typeof import('./src/components/MenHeader.vue')['default']
    MenProductLayout: typeof import('./src/components/MenProductLayout.vue')['default']
    MenTab: typeof import('./src/components/MenTab.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuNav: typeof import('./src/components/MenuNav.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    PerfumeProductLayout: typeof import('./src/components/PerfumeProductLayout.vue')['default']
    ProductListComponent: typeof import('./src/components/ProductListComponent.vue')['default']
    ReceiptComponent: typeof import('./src/components/ReceiptComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    UpdateProductComponent: typeof import('./src/components/updateProductComponent.vue')['default']
    WatchProductLayout: typeof import('./src/components/WatchProductLayout.vue')['default']
    WomenHeader: typeof import('./src/components/WomenHeader.vue')['default']
    WomenProductLayout: typeof import('./src/components/WomenProductLayout.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
